grails-app/domain/br/unirn/bd2/acesso/Pessoa.groovy
package br.unirn.bd2.acesso

import br.unirn.bd2.base.TipoPessoa

class Pessoa {

    String login
    String senha
    String senhaHash

    String matricula
    String nome
    TipoPessoa tipoPessoa
    String email

    static transients = ['senha']

    static constraints = {
        login nullable: false, blank: false, unique: true
        senha nullable: false, blank: false
        tipoPessoa nullable: false
        matricula nullable: true, unique: true
        nome nullable: true
        email nullable: true
    }

    def setSenha(String pass){
        if(pass){
            senha = pass
            senhaHash = senha.encodeAsSHA1()
        }
    }

    @Override
    String toString(){
        "${nome?:login} (${tipoPessoa})"
    }
}

grails-app/domain/br/unirn/bd2/base/Disciplina.groovy
package br.unirn.bd2.base

import br.unirn.bd2.acesso.Pessoa
import br.unirn.bd2.base.TipoPessoa

class Disciplina {

    String codigo
    String nome
    int cargaHoraria
    Pessoa professor

    static constraints = {
        codigo (unique: true, nullable: false)
        nome(nullable: false )
        cargaHoraria(min: 0, max: 360)
        professor ( nullable: true, validator: { val ->
            if(!val) return true
            if( val?.tipoPessoa != TipoPessoa.PROFESSOR ) return ['tipoErrado']
        })
    }

    @Override
    String toString(){
        "${codigo?:"S/COD"} - ${nome?:"S/NOME"}"
    }
}

grails-app/domain/br/unirn/bd2/base/Nota.groovy
package br.unirn.bd2.base

import br.unirn.bd2.acesso.Pessoa

class Nota {

    float valor
    Pessoa aluno
    Disciplina disciplina

    Date dateCreated
    Date lastUpdated


    static constraints = {
        valor(min: 0F, max: 10F)
        aluno(nullable: false, validator: { val ->
            if( val?.tipoPessoa != TipoPessoa.ALUNO) return ["tipoErrado"]
        })
        disciplina(nullable: false)
    }
}

grails-app/controllers/br/unirn/bd2/acesso/PessoaController.groovy
package br.unirn.bd2.acesso

import br.unirn.bd2.base.Disciplina
import br.unirn.bd2.base.Nota

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class PessoaController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def scaffold = Pessoa

    def minhasNotas(Pessoa pessoa){
        def resultado = Nota.findAllByAluno(pessoa)
        def total = Nota.countByAluno(pessoa)
        render view: '../nota/index', model:[notaInstanceList:resultado, notaInstanceCount: total]
    }

    def minhasDisciplinas(Pessoa pessoa){
        def resultado = Disciplina.findAllByProfessor(pessoa)
        def total = Disciplina.countByProfessor(pessoa)
        render view: '../disciplina/index', model:[disciplinaInstanceList:resultado, disciplinaInstanceCount: total]
    }

/*
    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Pessoa.list(params), model: [pessoaInstanceCount: Pessoa.count()]
    }
*/

/*
    def show(Pessoa pessoaInstance) {
        respond pessoaInstance
    }
*/

/*
    def create() {
        respond new Pessoa(params)
    }
*/

/*
    @Transactional
    def save(Pessoa pessoaInstance) {
        if (pessoaInstance == null) {
            notFound()
            return
        }

        if (pessoaInstance.hasErrors()) {
            respond pessoaInstance.errors, view: 'create'
            return
        }

        pessoaInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'pessoa.label', default: 'Pessoa'), pessoaInstance.id])
                redirect pessoaInstance
            }
            '*' { respond pessoaInstance, [status: CREATED] }
        }
    }
*/

/*
    def edit(Pessoa pessoaInstance) {
        respond pessoaInstance
    }
*/

/*
    @Transactional
    def update(Pessoa pessoaInstance) {
        if (pessoaInstance == null) {
            notFound()
            return
        }

        if (pessoaInstance.hasErrors()) {
            respond pessoaInstance.errors, view: 'edit'
            return
        }

        pessoaInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Pessoa.label', default: 'Pessoa'), pessoaInstance.id])
                redirect pessoaInstance
            }
            '*' { respond pessoaInstance, [status: OK] }
        }
    }
*/

/*
    @Transactional
    def delete(Pessoa pessoaInstance) {

        if (pessoaInstance == null) {
            notFound()
            return
        }

        pessoaInstance.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Pessoa.label', default: 'Pessoa'), pessoaInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }
*/

/*
    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'pessoa.label', default: 'Pessoa'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
*/

}

grails-app/views/pessoa/_form.gsp
<%@ page import="br.unirn.bd2.acesso.Pessoa" %>


<div class="fieldcontain ${hasErrors(bean: pessoaInstance, field: 'login', 'error')} required">
	<label for="login">
		<g:message code="pessoa.login.label" default="Login" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="login" required="" value="${pessoaInstance?.login}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: pessoaInstance, field: 'senha', 'error')} required">
	<label for="senha">
		<g:message code="pessoa.senha.label" default="Senha" />
		<span class="required-indicator">*</span>
	</label>
	<g:passwordField name="senha" required="" value="${pessoaInstance?.senha}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: pessoaInstance, field: 'nome', 'error')}">
	<label for="nome">
		<g:message code="pessoa.nome.label" default="Nome" />
	</label>
	<g:textField name="nome" required="" value="${pessoaInstance?.nome}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: pessoaInstance, field: 'matricula', 'error')}">
	<label for="matricula">
		<g:message code="pessoa.matricula.label" default="Matrícula" />
	</label>
	<g:textField name="matricula" value="${pessoaInstance?.matricula}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: pessoaInstance, field: 'email', 'error')}">
	<label for="email">
		<g:message code="pessoa.email.label" default="Email" />
	</label>
	<g:field type="email" name="email" value="${pessoaInstance?.email}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: pessoaInstance, field: 'tipoPessoa', 'error')} required">
	<label for="tipoPessoa">
		<g:message code="pessoa.tipoPessoa.label" default="Tipo Pessoa" />
		<span class="required-indicator">*</span>
	</label>
	<g:select name="tipoPessoa" from="${br.unirn.bd2.base.TipoPessoa?.values()}" keys="${br.unirn.bd2.base.TipoPessoa.values()*.name()}" required="" value="${pessoaInstance?.tipoPessoa?.name()}" />
</div>

grails-app/views/pessoa/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'pessoa.label', default: 'Pessoa')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-pessoa" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-pessoa" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${pessoaInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${pessoaInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:pessoaInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/pessoa/edit.gsp
<%@ page import="br.unirn.bd2.acesso.Pessoa" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'pessoa.label', default: 'Pessoa')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-pessoa" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-pessoa" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${pessoaInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${pessoaInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:pessoaInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${pessoaInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/pessoa/index.gsp
<%@ page import="br.unirn.bd2.acesso.Pessoa" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'pessoa.label', default: 'Pessoa')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>

	<body>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-pessoa" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>


			<table class="table table-bordered table-condensed table-hover">
				<thead>
				<tr class="warning">

					<g:sortableColumn property="login" title="${message(code: 'pessoa.login.label', default: 'Login')}" />

					<g:sortableColumn property="nome" title="${message(code: 'pessoa.nome.label', default: 'Nome')}" />

					<g:sortableColumn property="tipoPessoa" title="${message(code: 'pessoa.tipoPessoa.label', default: 'Tipo Pessoa')}" />

					<g:sortableColumn property="email" title="${message(code: 'pessoa.email.label', default: 'Email')}" />

					<g:sortableColumn property="senhaHash" title="${message(code: 'pessoa.senhaHash.label', default: 'Senha Hash')}" />

				</tr>
				</thead>
				<tbody>
				<g:each in="${pessoaInstanceList}" status="i" var="pessoaInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

						<td><g:link action="show" id="${pessoaInstance.id}">${fieldValue(bean: pessoaInstance, field: "login")}</g:link></td>

						<td>${fieldValue(bean: pessoaInstance, field: "nome")}</td>

						<td>${fieldValue(bean: pessoaInstance, field: "tipoPessoa")}</td>

						<td>${fieldValue(bean: pessoaInstance, field: "email")}</td>

						<td>${fieldValue(bean: pessoaInstance, field: "senhaHash")}</td>

					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${pessoaInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/pessoa/minhasDisciplinas.gsp
<%@ page import="br.unirn.bd2.base.Disciplina" %>
<!DOCTYPE html>
<html>
<head>
	<meta name="layout" content="main">
	<g:set var="entityName" value="${message(code: 'disciplina.label', default: 'Disciplina')}" />
	<title><g:message code="default.list.label" args="[entityName]" /></title>
</head>
<body>
<div class="nav" role="navigation">
	<ul>
		<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
		<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
	</ul>
</div>
<div id="list-disciplina" class="content scaffold-list" role="main">
	<h1><g:message code="default.list.label" args="[entityName]" /></h1>
	<g:if test="${flash.message}">
		<div class="message" role="status">${flash.message}</div>
	</g:if>
	<table class="table table-bordered table-condensed table-hover">
		<thead>
		<tr class="warning">

			<g:sortableColumn property="codigo" title="${message(code: 'disciplina.codigo.label', default: 'Codigo')}" />

			<g:sortableColumn property="nome" title="${message(code: 'disciplina.nome.label', default: 'Nome')}" />

			<g:sortableColumn property="cargaHoraria" title="${message(code: 'disciplina.cargaHoraria.label', default: 'Carga Horaria')}" />

			<th><g:message code="disciplina.professor.label" default="Professor" /></th>

		</tr>
		</thead>
		<tbody>
		<g:each in="${disciplinaInstanceList}" status="i" var="disciplinaInstance">
			<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

				<td><g:link action="show" id="${disciplinaInstance.id}">${fieldValue(bean: disciplinaInstance, field: "codigo")}</g:link></td>

				<td>${fieldValue(bean: disciplinaInstance, field: "nome")}</td>

				<td>${fieldValue(bean: disciplinaInstance, field: "cargaHoraria")}</td>

				<td>${fieldValue(bean: disciplinaInstance, field: "professor")}</td>

			</tr>
		</g:each>
		</tbody>
	</table>
	<div class="pagination">
		<g:paginate total="${disciplinaInstanceCount ?: 0}" />
	</div>
</div>
</body>
</html>

grails-app/views/pessoa/minhasNotas.gsp
<%@ page import="br.unirn.bd2.base.Nota" %>
<!DOCTYPE html>
<html>
<head>
	<meta name="layout" content="main">
	<g:set var="entityName" value="${message(code: 'nota.label', default: 'Nota')}" />
	<title><g:message code="default.list.label" args="[entityName]" /></title>
</head>
<body>
<a href="#list-nota" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
<div class="nav" role="navigation">
	<ul>
		<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
		<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
	</ul>
</div>
<div id="list-nota" class="content scaffold-list" role="main">
	<h1><g:message code="default.list.label" args="[entityName]" /></h1>
	<g:if test="${flash.message}">
		<div class="message" role="status">${flash.message}</div>
	</g:if>
	<table class="table table-bordered table-condensed table-hover">
		<thead>
		<tr class="warning">

			<g:sortableColumn property="valor" title="${message(code: 'nota.valor.label', default: 'Valor')}" />

			<th><g:message code="nota.aluno.label" default="Aluno" /></th>

			<th><g:message code="nota.disciplina.label" default="Disciplina" /></th>

			<g:sortableColumn property="dateCreated" title="${message(code: 'nota.dateCreated.label', default: 'Date Created')}" />

			<g:sortableColumn property="lastUpdated" title="${message(code: 'nota.lastUpdated.label', default: 'Last Updated')}" />

		</tr>
		</thead>
		<tbody>
		<g:each in="${notaInstanceList}" status="i" var="notaInstance">
			<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

				<td><g:link action="show" id="${notaInstance.id}">${fieldValue(bean: notaInstance, field: "valor")}</g:link></td>

				<td>${fieldValue(bean: notaInstance, field: "aluno")}</td>

				<td>${fieldValue(bean: notaInstance, field: "disciplina")}</td>

				<td><g:formatDate date="${notaInstance.dateCreated}" /></td>

				<td><g:formatDate date="${notaInstance.lastUpdated}" /></td>

			</tr>
		</g:each>
		</tbody>
	</table>
	<div class="pagination">
		<g:paginate total="${notaInstanceCount ?: 0}" />
	</div>
</div>
</body>
</html>

grails-app/views/pessoa/show.gsp
<%@ page import="br.unirn.bd2.acesso.Pessoa" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'pessoa.label', default: 'Pessoa')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-pessoa" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-pessoa" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list pessoa">
			
				<g:if test="${pessoaInstance?.login}">
				<li class="fieldcontain">
					<span id="login-label" class="property-label"><g:message code="pessoa.login.label" default="Login" /></span>
					
						<span class="property-value" aria-labelledby="login-label"><g:fieldValue bean="${pessoaInstance}" field="login"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${pessoaInstance?.nome}">
				<li class="fieldcontain">
					<span id="nome-label" class="property-label"><g:message code="pessoa.nome.label" default="Nome" /></span>
					
						<span class="property-value" aria-labelledby="nome-label"><g:fieldValue bean="${pessoaInstance}" field="nome"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${pessoaInstance?.tipoPessoa}">
				<li class="fieldcontain">
					<span id="tipoPessoa-label" class="property-label"><g:message code="pessoa.tipoPessoa.label" default="Tipo Pessoa" /></span>
					
						<span class="property-value" aria-labelledby="tipoPessoa-label"><g:fieldValue bean="${pessoaInstance}" field="tipoPessoa"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${pessoaInstance?.email}">
				<li class="fieldcontain">
					<span id="email-label" class="property-label"><g:message code="pessoa.email.label" default="Email" /></span>
					
						<span class="property-value" aria-labelledby="email-label"><g:fieldValue bean="${pessoaInstance}" field="email"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${pessoaInstance?.senhaHash}">
				<li class="fieldcontain">
					<span id="senhaHash-label" class="property-label"><g:message code="pessoa.senhaHash.label" default="Senha Hash" /></span>
					
						<span class="property-value" aria-labelledby="senhaHash-label"><g:fieldValue bean="${pessoaInstance}" field="senhaHash"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:pessoaInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${pessoaInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>