grails-app/controllers/br/unirn/bd2/acesso/AutenticacaoController.groovy
package br.unirn.bd2.acesso

class AutenticacaoController {

    def index() { }

    def login(){
        def login = params?.login
        String senha = params?.senha
        def usuario = Pessoa.findByLoginAndSenhaHash( login, senha?.encodeAsSHA1() )
        if(usuario) {
            session.usuario = usuario
            redirect controller: 'index', action: 'index'
            return
        }
        else{
            flash.message = "login/senha incorreto(s)..."
            redirect action: 'index'
            return
        }
    }

    def logout(){
        if(session.usuario) {
            session.invalidate()
        }
        redirect action: 'index'
    }
}

grails-app/views/layouts/_myfooter.gsp
	<hr />
    %{--<g:dataHoje/> Grapher/Marcio <g:anoAtual /><br>--}%
    <a href='http://getbootstrap.com/' target='_blank' data-toggle="tooltip" data-placement="top" title="Ir para página inicial do Twitter-Bootstrap">Twitter-Bootstrap</a>
    <a href="http://grails.org" target="_blank" data-toggle="tooltip" data-placement="right" title="Ir para página inicial do grails">
        <asset:image src="favicon.ico" alt="Grails Home" /> Grails Home
    </a>

    %{--<g:copyright anoInicio='2013'>"Yo quiero me atrepar em pe de cueco!"</g:copyright><br>--}%
    %{--<asset:image src="grails_logo.png" />--}%

grails-app/views/layouts/_myheader.gsp
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                %{--<span class="icon-bar"></span>--}%
                %{--<span class="icon-bar"></span>--}%
                %{--<span class="icon-bar"></span>--}%
            </button>
            <g:link class="navbar-brand" controller="index" data-toggle="tooltip" data-placement="bottom" title="Home">CadNotas</g:link>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li><g:link url="[action:'info', controller:'index']" data-toggle="tooltip" data-placement="bottom" title="Informações sobre a Aplicação, Cadastros Auxiliares" >Informações</g:link></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Opções<span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Action</a></li>
                    <li class="divider"></li>

                    <li class="dropdown-submenu"> <a tabindex="-1" href="#">Styled Marker</a>
                        <ul class="dropdown-menu">
                            <li><g:link controller="principal" action="styledMarkerEx">SM Examples</g:link></li>
                            <li><g:link controller="principal" action="styledMarkerRef">SM Reference</g:link></li>
                            <li class="dropdown-submenu"> <a href="#">More..</a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Level 3</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>

                    <li class="dropdown-submenu"> <a tabindex="-1" href="#">Marker Clusterer Plus</a>
                        <ul class="dropdown-menu">
                            <li><g:link controller="principal" action="markerClustererEx">MCP Examples</g:link></li>
                            <li><g:link controller="principal" action="markerClustererRef">MCP Reference</g:link></li>
                            <li class="dropdown-submenu"> <a href="#">More..</a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Level 3</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>

        </ul>

        <ul class="nav navbar-nav navbar-right">
           %{-- <g:if test="${!session?.usuario}">
                <g:form controller="autenticacao" action="login" method="post"
                        class="navbar-form" role="form">
                    <div class="form-group">
                        <input type="text" name="login" placeholder="Login" class="form-control input-sm">
                    </div>
                    <div class="form-group">
                        <input type="password" name="senha" placeholder="Senha" class="form-control input-sm">
                    </div>
                    <button type="submit" class="btn btn-primary btn-sm">Entrar</button>
                </g:form>
            </g:if>

            <g:else>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">${session?.usuario} <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><g:link controller="pessoa" action="show" id="${session?.usuario?.id}">Detalhes</g:link></li>
                        <li class="divider"></li>
                        <li><g:link controller="autenticacao" action="logout">Sair</g:link></li>
                    </ul>
                </li>
            </g:else>--}%

            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">${session?.usuario} <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                    <li><g:link controller="pessoa" action="show" id="${session?.usuario?.id}">Detalhes</g:link></li>

                    <g:if test="${session?.usuario?.tipoPessoa==br.unirn.bd2.base.TipoPessoa.ALUNO}">
                        <li><g:link controller="pessoa" action="minhasNotas" resource="${session?.usuario}" id="${session?.usuario?.id}">Minhas Notas</g:link></li>
                    </g:if>
                    <g:if test="${session?.usuario?.tipoPessoa==br.unirn.bd2.base.TipoPessoa.PROFESSOR}">
                        <li><g:link controller="pessoa" action="minhasDisciplinas" resource="${session?.usuario}" id="${session?.usuario?.id}">Minhas Disciplinas</g:link></li>
                    </g:if>

                    <li class="divider"></li>
                    <li><g:link controller="autenticacao" action="logout">Sair</g:link></li>
                </ul>
            </li>
        </ul>

    </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

grails-app/views/layouts/main-backup.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title><g:layoutTitle default="Grails"/></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="shortcut icon" href="${assetPath(src: 'favicon.ico')}" type="image/x-icon">
		<link rel="apple-touch-icon" href="${assetPath(src: 'apple-touch-icon.png')}">
		<link rel="apple-touch-icon" sizes="114x114" href="${assetPath(src: 'apple-touch-icon-retina.png')}">
  		<asset:stylesheet src="application.css"/>
		<asset:javascript src="application.js"/>
		<g:layoutHead/>
	</head>
	<body>
		<div id="grailsLogo" role="banner"><a href="http://grails.org"><asset:image src="grails_logo.png" alt="Grails"/></a></div>
		<g:layoutBody/>
		<div class="footer" role="contentinfo"></div>
		<div id="spinner" class="spinner" style="display:none;"><g:message code="spinner.alt" default="Loading&hellip;"/></div>
	</body>
</html>

grails-app/views/layouts/main.gsp
<%@ page import="org.codehaus.groovy.grails.io.support.GrailsResourceUtils; org.codehaus.groovy.grails.commons.spring.GrailsApplicationContext; grails.util.GrailsUtil" %>
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><g:layoutTitle default="Grails"/></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="${assetPath(src: 'favicon.ico')}" type="image/x-icon">
    <link rel="apple-touch-icon" href="${assetPath(src: 'apple-touch-icon.png')}">
    <link rel="apple-touch-icon" sizes="114x114" href="${assetPath(src: 'apple-touch-icon-retina.png')}">

    <asset:stylesheet src="application.css"/>
    <asset:javascript src="application.js"/>
    <g:layoutHead/>

    <style type="text/css">

    #footer {
        font-size: 0.75em;
        font-style: italic;
        padding: 2em 1em 2em 1em;
        margin-bottom: 1em;
        margin-top: 1em;
        clear: both;
    }

    /*requerido para usar navbar com navbar-fixed-top */
    body { padding-top: 50px; }
    </style>
</head>
<body>

<g:render template="/layouts/myheader" />

<br/>
<div class="row">
    <div class="col-lg-offset-1 col-lg-10">
        <div class="alert alert-info">
            <g:layoutBody/>

            %{--
            <div id="footer" class="footer text-center" role="contentinfo">
                <g:render template="/layouts/myfooter" />
            </div>
            --}%
        </div>
    </div>

    <g:javascript>
        $("[data-toggle=tooltip]").tooltip();
    </g:javascript>
</div>

</body>
</html>